version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run:
          name: install
          command: npm install --only=dev
      - run:
          name: lint
          command: npx eslint --fix-dry-run 'types/*'
      - run:
          name: integration test
          command: npm run test
