version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:10.13.0
      # Run Plug node
      - image: plugnet/plugblockchain:1.0.0-rc3.1
        entrypoint: /usr/local/bin/plug
        command:
          - --dev
          - --unsafe-ws-external
    steps:
      - checkout
      - run:
          name: Install
          command: npm i -f
      - run:
          name: Lint
          command: npx eslint --fix-dry-run 'types/*'
      - setup_remote_docker
      - run:
          name: Integration Tests
          command:
            npm install --only=dev && npm run test
